# Generated by Django 3.2.3 on 2021-06-07 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('nro_chip', models.IntegerField(primary_key=True, serialize=False)),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.raza')),
            ],
        ),
    ]
