# Generated by Django 3.2.3 on 2021-06-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro',
            old_name='nro_chip',
            new_name='Nro_chip',
        ),
        migrations.RenameField(
            model_name='perro',
            old_name='raza',
            new_name='Raza',
        ),
        migrations.RenameField(
            model_name='raza',
            old_name='descripcion',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='raza',
            old_name='id',
            new_name='IDRaza',
        ),
        migrations.RenameField(
            model_name='raza',
            old_name='nombre',
            new_name='Raza',
        ),
        migrations.AddField(
            model_name='perro',
            name='Adapt',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='C_gatos',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='C_ninos',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='C_perros',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='Edad_Perro',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='Energia',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='Esteril',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='Nombre_Perro',
            field=models.CharField(default=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='Nro_tel',
            field=models.IntegerField(null=True),
        ),
    ]
