# Generated by Django 3.2.3 on 2021-06-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210608_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='Nombre_Perro',
            field=models.CharField(default=True, max_length=99),
        ),
    ]
