# Generated by Django 3.2.3 on 2021-06-08 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_perro_nombre_perro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='Adapt',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='perro',
            name='C_gatos',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='perro',
            name='C_ninos',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='perro',
            name='C_perros',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='perro',
            name='Energia',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='perro',
            name='Esteril',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='perro',
            name='Nombre_Perro',
            field=models.CharField(max_length=99),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
