# Generated by Django 3.2.3 on 2021-06-08 20:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210608_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='imagen',
            field=models.ImageField(blank=True, max_length=9999, null=True, upload_to=core.models.Perro.ruta_imagen),
        ),
    ]
