# Generated by Django 3.2.3 on 2021-06-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perro_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='Sexo',
            field=models.CharField(default=True, max_length=99),
        ),
    ]
