# Generated by Django 3.2.3 on 2021-06-09 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perro_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='Nro_tel',
        ),
    ]
