# Generated by Django 3.2.3 on 2021-06-09 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_perro_nro_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raza',
            old_name='IDRaza',
            new_name='id',
        ),
    ]
