# Generated by Django 3.2.3 on 2021-06-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_idraza_raza_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='Sexo',
            field=models.CharField(max_length=99),
        ),
    ]
